[colors]
foreground = "#f1f1f1"
background = "#0a0a0a"
cursor_fg = "#0a0a0a"
cursor_bg = "#f1f1f1"
selection_fg = "#f1f1f1"
selection_bg = "#323232"

ansi = [
  "#1e1e1e",
  "#b9a0a0",
  "#a0b9a0",
  "#b9b0a0",
  "#a0a0b9",
  "#b0a0b9",
  "#a0b0b0",
  "#c1c1c1",
]

brights = [
  "#323232",
  "#b9a0a0",
  "#a0b9a0",
  "#b9b0a0",
  "#a0a0b9",
  "#b0a0b9",
  "#a0b0b0",
  "#d9d9d9",
]

[metadata]
name = "zen"
author = "nendix"
