# zen colorscheme for Alacritty
# https://github.com/nendix/zen.nvim

[colors.primary]
foreground = "#e0e0e0"
background = "#121212"

[colors.cursor]
text = "#121212"
cursor = "#e0e0e0"

[colors.selection]
text = "#e0e0e0"
background = "#323232"

[colors.normal]
black = "#222222"
red = "#b9a0a0"
green = "#a0b9a0"
yellow = "#b9b0a0"
blue = "#a0a0b9"
magenta = "#b0a0b9"
cyan = "#a0b0b0"
white = "#b2b2b2"

[colors.bright]
black = "#323232"
red = "#b9a0a0"
green = "#a0b9a0"
yellow = "#b9b0a0"
blue = "#a0a0b9"
magenta = "#b0a0b9"
cyan = "#a0b0b0"
white = "#d0d0d0"
