# zen flavor for Yazi
# https://github.com/nendix/zen.nvim
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[mgr]
cwd = { fg = "#9e9e9e" }

# Hovered
hovered         = { bg = "#222222" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#a0b9a0", bold = true, italic = true, underline = true }
find_position = { fg = "#b0a0b9", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#a0b9a0", bg = "#a0b9a0" }
marker_cut      = { fg = "#b9a0a0", bg = "#b9a0a0" }
marker_marked   = { fg = "#a0b0b0", bg = "#a0b0b0" }
marker_selected = { fg = "#b0a0b9", bg = "#b0a0b9" }

# Count
count_copied   = { fg = "#121212", bg = "#a0b9a0" }
count_cut      = { fg = "#121212", bg = "#b9a0a0" }
count_selected = { fg = "#121212", bg = "#b0a0b9" }

# Border
border_symbol = "â”‚"
border_style  = { fg = "#323232" }

[tabs]
active   = { fg = "#e0e0e0", bg = "#323232", bold = true }
inactive = { fg = "#767676", bg = "#1a1a1a" }

sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "#121212", bg = "#d0d0d0", bold = true }
normal_alt  = { fg = "#b2b2b2", bg = "#323232" }

select_main = { fg = "#121212", bg = "#b0a0b9", bold = true }
select_alt  = { fg = "#b0a0b9", bg = "#323232" }

unset_main = { fg = "#121212", bg = "#b9a0a0", bold = true }
unset_alt  = { fg = "#b9a0a0", bg = "#323232" }

[status]
overall   = { fg = "#9e9e9e" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep   = { fg = "#767676" }
perm_type  = { fg = "#a0a0b9" }
perm_read  = { fg = "#a0b9a0" }
perm_write = { fg = "#b9a0a0" }
perm_exec  = { fg = "#b9b0a0" }

# Progress
progress_label  = { fg = "#e0e0e0", bold = true }
progress_normal = { fg = "#a0b9a0", bg = "#323232" }
progress_error  = { fg = "#c07070", bg = "#323232" }

[which]
cols            = 3
mask            = { bg = "#1a1a1a" }
cand            = { fg = "#a0b0b0" }
rest            = { fg = "#767676" }
desc            = { fg = "#9e9e9e" }
separator       = "  "
separator_style = { fg = "#767676" }

[confirm]
border     = { fg = "#323232" }
title      = { fg = "#e0e0e0" }
content    = { fg = "#9e9e9e" }
list       = { fg = "#b2b2b2" }
btn_yes    = { fg = "#121212", bg = "#a0b9a0" }
btn_no     = { fg = "#121212", bg = "#b9a0a0" }
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[spot]
border   = { fg = "#323232" }
title    = { fg = "#e0e0e0" }
tbl_col  = { fg = "#b0a0b9" }
tbl_cell = { fg = "#a0a0b9", reversed = true }

[notify]
title_info  = { fg = "#6090a0" }
title_warn  = { fg = "#a09060" }
title_error = { fg = "#c07070" }

icon_info  = ""
icon_warn  = ""
icon_error = ""

[pick]
border   = { fg = "#323232" }
active   = { fg = "#e0e0e0", bg = "#323232", bold = true }
inactive = { fg = "#9e9e9e" }

[input]
border   = { fg = "#323232" }
title    = { fg = "#e0e0e0" }
value    = { fg = "#b2b2b2" }
selected = { reversed = true }

[cmp]
border   = { fg = "#323232" }
active   = { reversed = true }
inactive = { fg = "#9e9e9e" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "#323232" }
title   = { fg = "#e0e0e0" }
hovered = { fg = "#b0a0b9", bold = true }

[help]
on      = { fg = "#a0b0b0" }
run     = { fg = "#b0a0b9" }
desc    = { fg = "#9e9e9e" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#767676", bg = "#1a1a1a" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#b9b0a0" },
	# Media
	{ mime = "{audio,video}/*", fg = "#b0a0b9" },
	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#b9a0a0" },
	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#a0b0b0" },
	# Fallback
	{ name = "*", is = "orphan", bg = "#c07070" },
	{ name = "*", is = "exec", fg = "#a0b9a0" },
	{ name = "*/", fg = "#a0a0b9" }
]
